---
- name: Install MariaDB and open ports
  hosts: mariadbs
  ansible_user: stas
  become: true

  tasks:
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB service
      systemd:
        name: mysql
        state: started
        enabled: true

    - name: Open MariaDB ports
      ufw:
        rule: allow
        port: 3306
        proto: tcp
